#!/usr/bin/python3
"""Factorize all the things!."""
import sys

with open(sys.argv[1], "r") as file:
    lines = file.read().split('\n')
    for idx, line in enumerate(lines):
        if idx < len(lines) - 1:
            num = int(line)
            for i in range(2, (num // 2) + 1):
                if num % i == 0:
                    print("{:d}={:d}*{:d}".format(num, num // i, i))
                    break
